
#
# Sprinkle - Asset management library
#
# @author        Edmundas Kondra≈°ovas <as@edmundask.lt>
# @license       http://www.opensource.org/licenses/MIT
#

'(:default)':
  assets:
    - js-libs
    - global-styles
  replace:
  exclude:

'(client-forms)':
  assets:
    - js-libs
    - jquery-ui
    - accordion
    - accordion-css
  replace:
  exclude:

'(contact)':
  assets:
    - form-handlers
  replace:
  exclude:

'(staff)':
  assets:
    - fancybox-group
  replace:
  exclude:

'(map)':
  assets:
    - google-map
  replace:
  exclude:
